# apiVersion: storage.k8s.io/v1
# kind: StorageClass
# metadata:
#   name: aws-ebs-sc
# provisioner: ebs.csi.aws.com
# volumeBindingMode: WaitForFirstConsumer
# allowedTopologies:
# - matchLabelExpressions:
#   - key: topology.ebs.csi.aws.com/zone
#     values:
#     - us-east-1a


apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: aws-ebs-sc
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
allowedTopologies:
- matchLabelExpressions:
  - key: topology.ebs.csi.aws.com/zone
    values:
    - us-east-1a