apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: lu-crt
spec:
  secretName: lu-tls
  dnsNames:
  - "lupress.cloud-stacks.com"
  issuerRef:
    name: letsencrypt-issuer
    kind: ClusterIssuer